# Generated by Django 6.0.6 on 2026-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_role_employeeinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('owner', 'Owner'), ('manager', 'Manager'), ('salesman', 'Salesman')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('owner', 'Owner'), ('manager', 'Manager'), ('salesman', 'Salesman')], default='customer', max_length=20),
        ),
    ]
