# Generated by Django 6.0.6 on 2026-06-18 14:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='POSShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('opening_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('paused', 'Paused')], default='open', max_length=20)),
                ('opening_note', models.TextField(blank=True, default='')),
                ('closing_note', models.TextField(blank=True, default='')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_shifts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opening_time'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='POS.posshift'),
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('terminal_code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_terminals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='posshift',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='POS.posterminal'),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reconciled', 'Reconciled'), ('disputed', 'Disputed')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_cash_registers', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_cash_registers', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register', to='POS.posshift')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='POS.posterminal')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='POS.posterminal'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('movement_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('petty_cash', 'Petty Cash'), ('expense', 'Expense'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('note', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='POS.cashregister')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='POS.posshift')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['register', 'movement_type'], name='POS_cashmov_registe_1fdd56_idx'), models.Index(fields=['shift'], name='POS_cashmov_shift_i_e345ca_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['terminal', 'status'], name='POS_posshif_termina_8dc99a_idx'),
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['cashier', 'status'], name='POS_posshif_cashier_664a57_idx'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['terminal', 'status'], name='POS_cashreg_termina_7e8fff_idx'),
        ),
    ]
